version: "3"
services:
  api_server:
    image: test:latest
    ports:
      - "100:100"
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30