from global_config import qiniu_access_key,qiniu_secret_key,appSecret
pdf_url1 = "http://222.31.49.139/jwglxt/bysxxcx/xscjzbdy_cxXsCount.html?gnmkdm=N558020"
pdf_url2 = "http://222.31.49.139/jwglxt/bysxxcx/xscjzbdy_dyList.html?gnmkdm=N558020"
excel_url = "http://222.31.49.139/jwglxt/cjcx/cjcx_dcListByXs.html"
post_data = [
    ("gnmkdmKey", "N305005"),
    ("dcclbh", "JW_N305005_XSCXCJ"),
    ("queryModel.sortName", ""),
    ("queryModel.sortOrder", "asc"),
    ("exportModel.selectCol", "xnmmc@学年"),
    ("exportModel.selectCol", "xqmmc@学期"),
    ("exportModel.selectCol", "kch@课程代码"),
    ("exportModel.selectCol", "kcmc@课程名称"),
    ("exportModel.selectCol", "kcxzmc@课程性质"),
    ("exportModel.selectCol", "xf@学分"),
    ("exportModel.selectCol", "cj@成绩"),
    ("exportModel.selectCol", "bfzcj@百分制成绩"),
    ("exportModel.selectCol", "cjbz@成绩备注"),
    ("exportModel.selectCol", "jd@绩点"),
    ("exportModel.selectCol", "ksxz@成绩性质"),
    ("exportModel.selectCol", "cjsfzf@是否成绩作废"),
    ("exportModel.selectCol", "sfxwkc@是否学位课程"),
    ("exportModel.selectCol", "kkbmmc@开课学院"),
    ("exportModel.selectCol", "kcbj@课程标记"),
    ("exportModel.selectCol", "kclbmc@课程类别"),
    ("exportModel.selectCol", "kcgsmc@课程归属"),
    ("exportModel.selectCol", "jxbmc@教学班"),
    ("exportModel.selectCol", "jsxm@任课教师"),
    ("exportModel.selectCol", "khfsmc@考核方式"),
    ("exportModel.selectCol", "xh@学号"),
    ("exportModel.selectCol", "xm@姓名"),
    ("exportModel.selectCol", "xb@性别"),
    ("exportModel.selectCol", "xslb@学生类别"),
    ("exportModel.selectCol", "jgmc@学院"),
    ("exportModel.selectCol", "zymc@专业"),
    ("exportModel.selectCol", "njmc@年级"),
    ("exportModel.selectCol", "bj@班级"),
    ("exportModel.exportWjgs", "xls"),
    ("fileName", "grade-export")
]
